apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myappication
  template:
    metadata:
      labels:
        app: myappication
    spec:
      containers:
        - name: guru
          image: guru1998/guruweb:2.1.0
          ports:
            - containerPort: 8080

         
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myappication
